import { TRAVEL_TIME_FROM } from '../data/spots'

// Deterministic plan report built entirely from data already on screen
// (prefs summary + explanation from the LLM call already paid for, plus the
// scoring breakdown) - no extra LLM call, no extra token cost.
export function generatePlanReport({ prefsSummary, explanation, scored }) {
  const lines = []
  lines.push('CNR - Craft N Roam')
  lines.push('Trip Plan Report')
  lines.push(`Generated: ${new Date().toLocaleString()}`)
  lines.push('')
  lines.push('Destination: Nice, France')
  if (prefsSummary) lines.push(`Your interests: "${prefsSummary}"`)
  lines.push('')
  lines.push('RANKED PLAN')
  scored.forEach(({ spot, score, breakdown }, i) => {
    const label = i === 0 ? '  (TOP PICK)' : ''
    lines.push(`${i + 1}. ${spot.name} - Score ${(score * 100).toFixed(0)}/100${label}`)
    lines.push(
      `   ~${spot.travelTimeMinutes} min walk from ${TRAVEL_TIME_FROM.replace(', on foot', '')}`
      + ` - ${spot.durationHours} hr visit - cost level ${spot.costLevel}/5`,
    )
    lines.push(`   ${spot.tagline}`)
    lines.push(
      `   match ${breakdown.categoryScore.toFixed(2)} - cost fit ${breakdown.costScore.toFixed(2)}`
      + ` - time fit ${breakdown.timeScore.toFixed(2)}`,
    )
    lines.push('')
  })
  if (explanation) {
    lines.push('WHY THIS PLAN')
    lines.push(explanation)
    lines.push('')
  }
  lines.push('Generated by CNR (Craft N Roam) - https://github.com/GongNT/travel-3d-simulator')
  return lines.join('\n')
}

export function downloadPlanReport(reportText) {
  const blob = new Blob([reportText], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'cnr-trip-plan.txt'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
